<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create' => 'إضافة',
    'Delete' => 'محو',
    'Description' => 'تفصيل',
    'App name' => 'اسم التطبيق',
    'File' => 'المستند',
    'Login' => 'الدخول',
    'Logout' => 'الخروج',
    'Mail' => 'عنوان إلكتروني',
    'N°' => 'رقم',
    'Name' => 'إسم عائلي',
    'Profession' => 'مهنة',
    'Professions' => 'مهن',
    'Reset' => 'محو',
    'Size' => 'حجم',
    'Stats' =>  'إحصائيات',
    'Search' => 'بحث',
    'Total' => 'إجمالي',
    'Type' => 'نوع',
    'Update' => 'تحديث',
    'Update {modelClass}: ' => 'تحديث {modelClass}:',
    'Upload' => 'تحميل',
    'User' => 'المستخدم',
];
